export {default as after} from "../images/After.jpg"
export {default as before} from "../images/Before.jpg"
export {default as logo} from "../images/ColorFul26.png"
export {default as home} from "../images/home.jpg"
export {default as aboutus} from "../images/AboutUs.jpg"